accounts/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('signup/', views.signup, name='signup')
]

investments/urls.py
from django.urls import path

from . import views

app_name = "investments"
urlpatterns = [
    path('', views.InvestmentListView.as_view(), name='index'),
    path("search/", views.search_investments, name="search"),
    path("create/", views.create_investment, name="create"),
    path("<int:investment_id>/", views.detail_investment, name="detail"),
    path("update/<int:investment_id>/", views.update_investment, name="update"),
    path("delete/<int:investment_id>/", views.delete_investment, name="delete"),
    path("<int:investment_id>/comentario/", views.create_comentario, name="comentario"),
    path("lists/", views.ListListView.as_view(), name="lists"),
    path("lists/create", views.ListCreateView.as_view(), name="create-list"),
    path('categorias/', views.categorias, name='categorias'),
    path('categorias/<str:categoria>/', views.posts_por_categoria, name='posts_por_categoria')
]

investmentsite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('staticpages.urls')),
    path('investments/', include('investments.urls')),
    path('accounts/', include('accounts.urls')),
     path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock %} InvesteProspera - Educação Financeira
    </title>
    <link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>

<body>
    <header id="cabecalho-principal">
        <a href="{% url 'index' %}"> <img src="{% static 'logo.svg' %}"> </a>
        <nav id="navegacao-principal">
            <ul>
                {% if user.is_authenticated %}
                    <li> Logado com {{ user.username }} </li>
                    <li><a href="{% url 'logout' %}">Log out</a></li>
                {% else %}
                    <li><a href="{% url 'login' %}">Log in</a></li>
                {% endif %}
                {% if not user.is_authenticated %}
                <li><a href="{% url 'signup' %}">Signup</a></li>
                {% endif %}
                <li><a href="{% url 'investments:index' %}">Artigos de Investimento</a></li>
                <li><a href="{% url 'investments:lists' %}">Favoritos da Comunidade</a></li>
                <li><a href="{% url 'investments:categorias' %}">Categorias</a></li>
                <li><a href="{% url 'about' %}">Sobre</a></li>
            </ul>
        </nav>

    </header>
    <main id="conteiner-principal">
        {% block content %}
        {% endblock content %}
    </main>
    <footer id="rodape-principal">
        <p>
            <small>Copyright 2023</small>
        </p>
    </footer>
</body>

</html>