accounts/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('signup/', views.signup, name='signup')
]

investments/urls.py
from django.urls import path

from . import views

app_name = "investments"
urlpatterns = [
    path('', views.InvestmentListView.as_view(), name='index'),
    path("search/", views.search_investments, name="search"),
    path("create/", views.create_investment, name="create"),
    path("<int:investment_id>/", views.detail_investment, name="detail"),
    path("update/<int:investment_id>/", views.update_investment, name="update"),
    path("delete/<int:investment_id>/", views.delete_investment, name="delete"),
    path("<int:investment_id>/comentario/", views.create_comentario, name="comentario"),
    path("lists/", views.ListListView.as_view(), name="lists"),
    path("lists/create", views.ListCreateView.as_view(), name="create-list"),
    path('categorias/', views.categorias, name='categorias'),
    path('categorias/<str:categoria>/', views.posts_por_categoria, name='posts_por_categoria')
]

investmentsite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('staticpages.urls')),
    path('investments/', include('investments.urls')),
    path('accounts/', include('accounts.urls')),
     path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

investments/models.py
from django.db import models
from django.conf import settings


class Investment(models.Model):
    name = models.CharField(max_length=255)
    categoria = models.CharField(max_length=255)
    image_url = models.URLField(max_length=200, null=True)
    texto = models.CharField(max_length=3000, null=True)
    data = models.DateField(auto_now_add=True)
    def __str__(self):
        return f"{self.name}"


class Comentario(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    text = models.CharField(max_length=255)
    likes = models.IntegerField(default=0)
    data = models.DateField(auto_now_add=True)
    investment = models.ForeignKey(Investment, on_delete=models.CASCADE)

    def __str__(self):
        return f'"{self.text}" - {self.author.username}'

class List(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    investments = models.ManyToManyField(Investment)

    def __str__(self):
        return f"{self.name} by {self.author}"

investments/forms.py
from django.forms import ModelForm
from .models import Investment, Comentario


class InvestmentForm(ModelForm):
    class Meta:
        model = Investment
        fields = [
            "name",
            "categoria",
            "image_url",
            "texto",
        ]
        labels = {
            "name": "Título",
            "categoria": "Categoria de Investimento",
            "image_url": "URL da Imagem",
            "texto": "Texto"
        }


class ComentarioForm(ModelForm):
    class Meta:
        model = Comentario
        fields = [
            "text",
        ]
        labels = {
            "text": "Comentário",
        }

investments/views.py
import requests

from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.shortcuts import render, get_object_or_404
from django.views import generic
from .models import Investment, Comentario, List
from .forms import InvestmentForm, ComentarioForm
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin


def detail_investment(request, investment_id):
    investment = get_object_or_404(Investment, pk=investment_id)
    if 'last_viewed' not in request.session:
        request.session['last_viewed'] = []
    request.session['last_viewed'] = [investment_id
                                      ] + request.session['last_viewed']
    if len(request.session['last_viewed']) > 5:
        request.session['last_viewed'] = request.session['last_viewed'][:-1]
    context = {'investment': investment}
    return render(request, 'investments/detail.html', context)

class InvestmentListView(generic.ListView):
    model = Investment
    template_name = 'investments/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if 'last_viewed' in self.request.session:
            context['last_investments'] = []
            for investment_id in self.request.session['last_viewed']:
                context['last_investments'].append(
                    get_object_or_404(Investment, pk=investment_id))
        return context


def search_investments(request):
    context = {}
    if request.GET.get('query', False):
        search_term = request.GET["query"].lower()
        investment_list = Investment.objects.filter(name__icontains=search_term)
        context = {"investment_list": investment_list}
    return render(request, "investments/search.html", context)


@login_required
@permission_required('investments.add_investment')
def create_investment(request):
    if request.method == 'POST':
        investment_form = InvestmentForm(request.POST)
        if investment_form.is_valid():
            investment = Investment(**investment_form.cleaned_data)
            investment.save()
            return HttpResponseRedirect(
                reverse('investments:detail', args=(investment.pk, )))

    else:
        investment_form = InvestmentForm()
    context = {"investment_form": investment_form}
    return render(request, "investments/create.html", context)

@login_required
@permission_required('investments.update_investment')
def update_investment(request, investment_id):
    investment = get_object_or_404(Investment, pk=investment_id)
    if request.method == "POST":
        form = InvestmentForm(request.POST)
        if form.is_valid():
            investment.name = form.cleaned_data["name"]
            investment.categoria = form.cleaned_data["categoria"]
            investment.image_url = form.cleaned_data["image_url"]
            investment.texto = form.cleaned_data["texto"]
            investment.save()
            return HttpResponseRedirect(reverse("investments:detail", args=(investment.id,)))
    else:
        form = InvestmentForm(
            initial={
                "name": investment.name,
                "categoria": investment.categoria,
                "image_url": investment.image_url,
                "texto": investment.texto,
            }
        )
    context = {"investment": investment, "form": form}
    return render(request, "investments/update.html", context)

@login_required
@permission_required('investments.delete_investment')
def delete_investment(request, investment_id):
    investment = get_object_or_404(Investment, pk=investment_id)

    if request.method == "POST":
        investment.delete()
        return HttpResponseRedirect(reverse("investments:index"))

    context = {"investment": investment}
    return render(request, "investments/delete.html", context)

@login_required
def create_comentario(request, investment_id):
    investment = get_object_or_404(Investment, pk=investment_id)
    if request.method == "POST":
        form = ComentarioForm(request.POST)
        if form.is_valid():
            comentario_author = request.user
            comentario_text = form.cleaned_data["text"]
            comentario = Comentario(author=comentario_author, text=comentario_text, investment=investment)
            comentario.save()
            return HttpResponseRedirect(reverse("investments:detail", args=(investment_id,)))
    else:
        form = ComentarioForm()
    context = {"form": form, "investment": investment}
    return render(request, "investments/comentario.html", context)


class ListListView(generic.ListView):
    model = List
    template_name = "investments/lists.html"


class ListCreateView(LoginRequiredMixin, PermissionRequiredMixin,
                     generic.CreateView):
    model = List
    template_name = 'investments/create_list.html'
    fields = ['name', 'author', 'investments']
    success_url = reverse_lazy('investments:lists')
    permission_required = 'investments.add_list'

def categorias(request):
    categorias = Investment.objects.values_list('categoria', flat=True).distinct()
    categorias_e_investimentos = {}
    
    for categoria in categorias:
        investimentos = Investment.objects.filter(categoria=categoria)
        categorias_e_investimentos[categoria] = investimentos

    return render(request, 'investments/categorias.html', {'categorias_e_investimentos': categorias_e_investimentos})

def posts_por_categoria(request, categoria):
    investimentos = Investment.objects.filter(categoria=categoria)
    return render(request, 'investments/posts_por_categoria.html', {'investimentos': investimentos, 'categoria': categoria})

investments/templates/investments/categorias.html
{% extends 'base.html' %}

{% block content %}
    <h2>Todas as Categorias</h2>
    <ul>
        {% for categoria, investimentos in categorias_e_investimentos.items %}
            <li><a href="{% url 'investments:posts_por_categoria' categoria=categoria %}">
                <u style="text-decoration: underline;">{{ categoria }}</u>
            </a></li>
            <ul>
                {% for investment in investimentos %}
                    <li>
                        <div style="margin-bottom: 10px;">
                            <strong>{{ investment.name }}</strong>
                        </div>
                        <a href="{% url 'investments:detail' investment.id %}">
                            <img src="{{ investment.image_url }}" alt="{{ investment.name }}" style="max-width: 200px; height: auto; display: block;">
                        </a>
                    </li>
                {% endfor %}
            </ul>
        {% endfor %}
    </ul>
{% endblock %}

investments/templates/investments/comentario.html
{% extends 'base.html' %}
{% block content %}
    <h2>Comentar Artigo {{ investment.name }} ({{ investment.categoria }})</h2>
    <form action="{% url 'investments:comentario' investment.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Postar Comentário</button>
    </form>
    <p>
        <a href="{% url 'investments:detail' investment.id %}">Voltar para a página do artigo</a>
    </p>
{% endblock content %}

investments/templates/investments/create.html
{% extends 'base.html' %}
{% block title %}
    Criar Artigo
{% endblock title %}
{% block content %}
    <h2>Adicionar Artigo de Investimento</h2>
    <form action="{% url 'investments:create' %}" method="post">
        {% csrf_token %}
        {{ investment_form.as_p }}
        <button type="submit">Criar</button>
    </form>
{% endblock content %}

investments/templates/investments/create_list.html
{% extends 'base.html' %}
{% block title %}
    Criar Artigo de Investimento
{% endblock title %}
{% block content %}
    <h2>Criar Lista de Artigos Favoritos</h2>
    <form action="{% url 'investments:create-list' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Criar</button>
    </form>
{% endblock content %}

investments/templates/investments/delete.html
{% extends 'base.html' %}
{% block content %}
    <form action="{% url 'investments:delete' investment.id %}" method="post">
        {% csrf_token %}
        <p>Você tem certeza que deseja apagar o artigo"{{ investment.name }} ({{ investment.categoria }})"?</p>
        <button type="submit">Apagar</button>
    </form>
{% endblock content %}

investments/templates/investments/detail.html
{% extends 'base.html' %}
{% block title %}
    <strong>{{ investment.name }}</strong> (<a href="{% url 'investments:posts_por_categoria' categoria=investment.categoria %}"><strong>{{ investment.categoria }}</strong></a>)
{% endblock title %}
{% block content %}
    <h2>{{ investment.name }}</h2>
    <section class="dados-de-investment">
        <img src="{{ investment.image_url }}" alt="Foto do artigo {{ investment.name }}">
        <ul>
            <li><u>Nome</u>: <strong>{{ investment.name }}</strong></li>
            <li><u>Categoria</u>: <strong><a href="{% url 'investments:posts_por_categoria' categoria=investment.categoria %}">{{ investment.categoria }}</a></strong></li>
            <li><u>Data de publicação</u>: <strong>{{investment.data}}</strong></li>
            <li><u>Texto</u>: {{ investment.texto }}</li>
            {% if investment.list_set.all %}<li><u>Incluso nas listas</u>: {{ investment.list_set.all|join:", " }}</li>{% endif %}
            <li>
                <a href="{% url 'investments:update' investment.id %}">Editar</a>
            </li>
            <li>
                <a href="{% url 'investments:delete' investment.id %}">Apagar</a>
            </li>
        </ul>
    </section>
    <hr>
    <section>
        <header>
            <h3>Comentários</h3>
        </header>
        <ul>
            {% if investment.comentario_set.all %}
                {% for comentario in investment.comentario_set.all|dictsortreversed:"id" %}
                    <figure>
                        <blockquote>
                            "{{ comentario.text }}"
                        </blockquote>
                        <figcaption>—{{ comentario.author }}, {{comentario.data}}</figcaption>
                    </figure>
                {% endfor %}
            {% else %}
                <p>Ainda não existe nenhum comentário para este artigo.</p>
            {% endif %}
        </ul>
        <hr>
        <a href="{% url 'investments:comentario' investment.pk %}">
            <button>Crie seu Comentário</button>
        </a>
    </section>
{% endblock content %}

investments/templates/investments/index.html
{% extends 'base.html' %}

{% block content %}
<h2>Todos os Artigos</h2>
<section>
    <p>Muitos resultados? <a href="{% url 'investments:search' %}">Buscar Artigos</a></p>
    {% if perms.investments.add_investment %}
        <p>Não encontrou o artigo? <a href="{% url 'investments:create' %}">Adicionar Novo Artigo</a></p>
    {% endif%}
</section>
{% if investment_list %}
<section class="lista-de-cards">
    {% for investment in investment_list %}
    <article class="card">
        <a href="{% url 'investments:detail' investment.id %}"><img src="{{ investment.image_url }}"
                alt="Foto do Artigo {{ investment.name}}"></a>
        <p>{{ investment.name }}</p>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum artigo.</p>
{% endif %}

{% if last_investments %}
<hr>
<h2>Últimos vistos</h2>
<section class="lista-de-cards">
    {% for last_investment in last_investments %}
    <article class="small-card">
        <a href="{% url 'investments:detail' last_investment.id %}"><img src="{{ last_investment.image_url }}"
                alt="Foto do artigo {{ last_investment.name}}"></a>
    </article>
    {% endfor %}
</section>
{% endif %}

{% endblock content %}

investments/templates/investments/lists.html
{% extends 'base.html' %}

{% block title %}
Listas
{% endblock title %}

{% block content %}
<h2>Favoritos da Comunidade</h2>

<section>
    {% for list in list_list %}
    <hr>
    <article>
        <header>
            <h3>{{list.name}} (de {{ list.author }}) </h3>
        </header>
        <div class="lista-de-cards">
            {% for investment in list.investments.all %}
            <div class="card">
                <a href="{% url 'investments:detail' investment.id %}"><img src="{{ investment.image_url }}"
                        alt="Foto do Artigo {{ investment.name}}"></a>
                <p>{{ investment.name }} ({{ investment.categoria }})</p>
            </div>
            {% endfor %}
        </div>
    </article>
    {% endfor %}

    <a href="{% url 'investments:create-list' %}"><button>Crie sua Lista</button></a>
</section>

{% endblock content %}

investments/templates/investments/posts_por_categoria.html
{% extends 'base.html' %}

{% block content %}
    <h2>Artigos da Categoria: {{ categoria }}</h2>
    <ul>
        {% for investment in investimentos %}
            <li>
                <div style="margin-bottom: 20px;">
                    <strong>{{ investment.name }}</strong>
                </div>
                <div>
                    <a href="{% url 'investments:detail' investment.id %}">
                        <img src="{{ investment.image_url }}" alt="{{ investment.name }}" style="max-width: 200px; height: auto; display: block;">
                    </a>
                </div>
            </li>
        {% empty %}
            <p>Nenhum artigo foi encontrado para esta categoria.</p>
        {% endfor %}
    </ul>
{% endblock %}

investments/templates/investments/search.html
{% extends 'base.html' %}

{% block content %}
<h2>Busca de Artigos por Nome</h2>
<form action="{% url 'investments:search' %}">
    <p>
        <label for="id_query">Título:</label>
        <input type="text" name="query" id="id_query" />
    </p>
    <button type="submit">Buscar</button>
</form>


<h2>Resultado da Busca</h2>
{% if investment_list %}
<section class="lista-de-cards">
    {% for investment in investment_list %}
    <article class="card">
        <img src="{{ investment.image_url }}" alt="Foto do artigo {{ investment.name}}">
        <p>{{ investment.name }} ({{ investment.categoria }})</p>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum artigo para a busca.</p>
{% endif %}

{% endblock content %}

investments/templates/investments/update.html
{% extends 'base.html' %}
{% block content %}
    <h2>Atualizar Dados do Artigo {{ investment.name }}</h2>
    <form method="POST" action="{% url 'investments:update' investment.id %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Atualizar</button>
    </form>
{% endblock content %}